language: python
python:
  - "3.7"
install:
  - pip install coverage==4.3
  #- pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov
script:
  #- pytest tests.py --cov-report=xml --cov=.
  #- codeclimate-test-reporter --file .coverage
  - coverage run -m pytest Tests/*tests.py --cov-report=xml --cov=.

after_success:
  - codecov